INSERT INTO AUTOR (ID, NOME) VALUES (1, 'Manoel Bandeira');
INSERT INTO AUTOR (ID, NOME) VALUES (2, 'Gracilianos Ramos');

INSERT INTO  LIVRO ( ID, NOME, QUANTIDADE_PAGINAS ) VALUES ( 1,' Use a cabeça Java',300 );
INSERT INTO  LIVRO ( ID, NOME, QUANTIDADE_PAGINAS ) VALUES ( 2,' Java como programar',500 );
INSERT INTO  LIVRO ( ID, NOME, QUANTIDADE_PAGINAS ) VALUES ( 3,' Spring boot',200 );